### ISSUE TITLE
Add ecsshutdown command

### ISSUE THREAD

**Issue by danellecline** [mbari-org/deepsea-ai#34]
This is a new feature request to add a shutdown command to halt any data processed with the ecsprocess command. e.g.

```
deepsea-ai ecsshutdown -u \
        --job "DocRicketts 2021/08 with benthic model" \
        --cluster benthic33k 
```
 
Tasks
- [x] Purge SQS VIDEO_QUEUE queue to halt any autoscaling
- [x] Forced shutdown of any running ECS tasks
- [x] Remove any completed video tracks from S3 as queued in the TRACK_QUEUE
- [x] Update job status in sqlite

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```
